# Generated by Django 6.1 on 2026-08-27 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255, verbose_name='اسم الجهاز / الموديل')),
                ('device_id', models.CharField(max_length=255, verbose_name='المعرف الفريد للجهاز')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ تسجيل الدخول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_session', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة جهاز',
                'verbose_name_plural': 'جلسات الأجهزة',
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
