# Generated by Django 6.1 on 2026-09-15 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المسابقة')),
                ('start_time', models.DateTimeField(verbose_name='تاريخ ووقت البدء (توقيت الأردن)')),
                ('entry_fee_coins', models.PositiveIntegerField(default=5, verbose_name='رسوم الدخول')),
                ('revive_cost_coins', models.PositiveIntegerField(default=5, verbose_name='تكلفة الفرصة الثانية')),
                ('is_active', models.BooleanField(default=False, verbose_name='جارية الآن')),
                ('is_finished', models.BooleanField(default=False, verbose_name='منتهية')),
            ],
            options={
                'verbose_name': 'مسابقة مباشرة',
                'verbose_name_plural': 'المسابقات المباشرة',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('option_a', models.CharField(max_length=255, verbose_name='الخيار A')),
                ('option_b', models.CharField(max_length=255, verbose_name='الخيار B')),
                ('option_c', models.CharField(max_length=255, verbose_name='الخيار C')),
                ('option_d', models.CharField(max_length=255, verbose_name='الخيار D')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط للاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سؤال في بنك الأسئلة',
                'verbose_name_plural': 'بنك الأسئلة',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ترتيب السؤال (1-15)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApi.questionbank', verbose_name='السؤال')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApi.livequiz', verbose_name='المسابقة')),
            ],
            options={
                'verbose_name': 'ترتيب سؤال في المسابقة',
                'verbose_name_plural': 'ترتيب أسئلة المسابقات',
                'ordering': ['order'],
                'unique_together': {('quiz', 'order')},
            },
        ),
        migrations.AddField(
            model_name='livequiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', through='quizApi.QuizQuestionOrder', to='quizApi.questionbank', verbose_name='أسئلة المسابقة'),
        ),
        migrations.CreateModel(
            name='QuizParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='النقاط')),
                ('is_eliminated', models.BooleanField(default=False, verbose_name='مستبعد / خسر')),
                ('is_spectator', models.BooleanField(default=False, verbose_name='مشاهد / ضيف')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApi.livequiz', verbose_name='المسابقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مشارك في المسابقة',
                'verbose_name_plural': 'المشاركون في المسابقات',
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
