# Generated by Django 6.1 on 2026-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='question_text',
            field=models.CharField(max_length=255, verbose_name='نص السؤال'),
        ),
    ]
