# Generated by Django 6.1 on 2026-09-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApi', '0002_livequiz_multiplechoicequestion_quizparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizparticipant',
            name='is_spectator',
            field=models.BooleanField(default=False, verbose_name='مشاهد / ضيف'),
        ),
    ]
