# Generated by Django 6.1 on 2026-09-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApi', '0002_alter_questionbank_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizparticipant',
            name='lives',
            field=models.IntegerField(default=2),
        ),
    ]
